replicaCount: 3

image:
  repository: bestrong
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  host: bestrong.local

resources:
  limits:
    memory: "256Mi"
    cpu: "200m"
  requests:
    memory: "128Mi"
    cpu: "100m"

containerPort: 80

labels:
  app: webapp
  tier: backend
