apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bestrong-tls
  namespace: default
spec:
  dnsNames:
    - bestrong.local
  secretName: bestrong-tls-secret
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: bestrong.local
