apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bestrong-webapp.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: bestrong-tls-secret
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bestrong-webapp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}